# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
    loader = {
      timeout = 30;
      efi = {
        efiSysMountPoint = "/boot/efi";
      };
      grub = {
        enable = true;
        theme = pkgs.nixos-grub2-theme;
        efiSupport = true;
        efiInstallAsRemovable = true; # Otherwise /boot/EFI/BOOT/BOOTX64.EFI isn't generated
        devices = ["nodev"];
        useOSProber = true;
        extraEntries = ''
          menuentry "Reboot" {
          	reboot
          }
          menuentry "Poweroff" {
          	halt
          }
        '';
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/5f2dbea4-8909-4bcc-b394-68621787142b";
      fsType = "ext4";
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/31CD-78A8";
      fsType = "vfat";
    };
  };

  swapDevices = [{device = "/dev/disk/by-uuid/b448595b-922c-4ebf-ac4d-37a2ce597072";}];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    bluetooth.enable = true;
    opengl.enable = true;
    opengl.driSupport32Bit = true; # Required for Steam
    pulseaudio.enable = false;
  };
}
